variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest
stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -s settings.xml -Pip-solr-indexing-hx"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:latest
    tags:
      - dind
    services:
      - docker:dind
  stage: package
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker --version
    - echo ${CONTAINER_IMAGE}
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"