image: docker:latest
services:
  - docker:dind
variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest
  DOCKER_TLS_CERTDIR: ""
stages:
  - build-jar
  - build-docker-image

maven-build:
  image: maven:3-jdk-8
  stage: build-jar
  script: "mvn package -B -s settings.xml -Pip-solr-indexing-hx"
  after_script:
    - "cp $CI_PROJECT_PATH/target/intact-search-interactors-ws-1.0.3-SNAPSHOT.jar target/"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build-docker-image
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker --version
    - echo ${CONTAINER_IMAGE}
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"